### ISSUE TITLE
checkout_id is not long enough

### ISSUE THREAD

**Issue by gillisig** [paddle-python/dj-paddle#27]
* dj-paddle version: 0.1.1
* Django version: 3.1
* Python version: 3.7
* Operating System: Linux

### Description

Subscription checkout_id has max_length of 32. However Paddle can send checkout_id's that are longer than that. In my instance I got a 35 character id.

**Comment by FPurchess** [comment]
Thanks @gillisig! 

I increased the field length for paddle IDs now to 64 chars.
Unfortunately their doc is quite poor in terms of clear definition of the length of the IDs.

**Comment by gillisig** [comment]
Awesome, thank you as well @FPurchess, this plugin saved me a lot of time.
