### ISSUE TITLE
Latest version needs to be released on PyPi

### ISSUE THREAD

**Issue by sebs-code** [paddle-python/dj-paddle#30]
* dj-paddle version:
* Django version:
* Python version:
* Operating System:

### Description

The latest version with the Checkout ID extended to 64 Chars is not on PyPy - it's still installing the old version. 

### What I Did
pip install dj-paddle

**Comment by Wolf-Byte** [comment]
Please could we get an update on when the next version is going to be released?

**Comment by FPurchess** [comment]
Hey @sebs-code and @Wolf-Byte, I just released a new version (https://github.com/paddle-python/dj-paddle/releases/tag/v0.1.2) for your convenience. However, the reason I was hesitant to do so before is, that the latest changes are not reflected by the documentation. While I'd love to see docs and releases go hand-in-hand, I'm lacking time to do so on my own right now and appreciate any support.
